### ISSUE TITLE
Required class diagram changes

### ISSUE THREAD

**Issue by Jake-L** [cp317/Design#27]
User:
- replace userName with userId (string)
- add beacons attribute as string[0..*]
- change joinBeacon parameter from Beacon to BeaconId 
- change leaveBeacon parameter from Beacon to BeaconId

Registered User:
- add hostBeaconId attribute (string)
- add firstName attribute (string)
- add lastName attribute (string)
- change constructor to RegisteredUser(string email, string firstName, string lastName)
- move getOpenBeacons to User class

Beacon:
- change members attribute type from User[1..*] to string[0..*] (host not counted as member)
- change host attribute type from RegisteredUser to string (use userId as foreign key)
- remove beacon parameter from closeBeacon and extendBeacon
- change id to BeaconId
- change relocateBeacon parameter from Beacon to double lat and double lng
- change addMember parameter to userId string
- combine both removeMember functions to a single removeMember function with parameter userId string
- change getMembers return type to string[0..*]

Course:
- remove course class entirely

Beacon Chat / Course Chat / Private Chat
- remove this classes entirely

**Comment by Amandeep-G** [comment]
Ok I've updated the database class diagram with these changes but for the normal class diagram, for things such as: "change host attribute type from RegisteredUser to string (use userId as foreign key)" , I left it as it is because we shouldn't be directly referencing attributes of other classes as it makes the classes tightly coupled.
