### ISSUE TITLE
Class diagram problems

### ISSUE THREAD

**Issue by garrettparris** [cp317/Design#6]
I'm not sure if these are problems or not.
why is user associated with course? User should not be associated with course
why is course associated with chat? not sure if each course should have a chat
beacon should have 1 instance of chat. 
User should only have 1 instance of beacon
beacon should have atleast one instance of course.

**Comment by garrettparris** [comment]
Also I think all instances of courseCode should be replaced with the Course object.

**Comment by Amandeep-G** [comment]
I'm assuming you are talking about the database class diagram, and the "classes" of this diagram are actually tables so they refer to courseCodes as foreign keys rather than course objects which are included in the normal class diagram.  Course has a chat as outlined in the requirements doc.

Users are associated with course in the same way as users take courses and we need to store the courses they take. Also they can be associated with multiple beacons if they decide to plan future beacons they will need to have these beacons stored/associated with them. 

And I will update the diagram so beacon has 1 instance of chat and atleast 1 course.

**Comment by Amandeep-G** [comment]
Updated diagram to reflect those changes.
